### ISSUE TITLE
What happened to the extension?

### ISSUE THREAD

**Issue by nkmathew** [cloeduc/wattpad_select_fiction#1]
Did you take it down or something?

**Comment by cloeduc** [comment]
Hi!
yes I took it down because I merged this feature with a bigger extension (https://github.com/cloeduc/wattpad_better)

**Comment by nkmathew** [comment]
Does that restore the right click menu? Tried it and it doesn't seem to

**Comment by cloeduc** [comment]
It works for me. Did you enable this feature on options ?

![image](https://cloud.githubusercontent.com/assets/1202130/25779403/3acdfe98-3317-11e7-8298-ed68788de8f2.png)

**Comment by nkmathew** [comment]
Worked on reload.
Thanks for this man. Wattpad has some stupid restrictions sometimes.

Looking forward to reading your articles

Please add a README and a note on the new extension. The lack of it makes the repo look abandoned. Was about to write my own before I saw the other one

**Comment by cloeduc** [comment]
Great if it works :)
Yup, I'll add readme.
I don't understand why I didn't add it before :/
